<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="VinhL" failures="4" tests="9" name="iPhone 13" time="0.614" errors="0" timestamp="2022-08-19T12:47:07 ICT">
  <testcase classname="tests.BaseTest" name="@AfterMethod captureScreenshot" time="0.002">
    <failure type="java.lang.IllegalArgumentException" message="Please provide env variable [env]!">
      <![CDATA[java.lang.IllegalArgumentException: Please provide env variable [env]!
at driver.DriverFactory.getDriver(DriverFactory.java:62)
at tests.BaseTest.getDriver(BaseTest.java:35)
at tests.BaseTest.captureScreenshot(BaseTest.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod captureScreenshot -->
  <testcase classname="tests.testng.TestNGHooks02" name="testSth01" time="0.007"/>
  <testcase classname="tests.testng.TestNGHooks02" name="testSth02" time="0.006"/>
  <testcase classname="tests.testng.TestParameter" name="testParameter" time="0.005"/>
  <testcase classname="tests.testng.TestParameter02" name="testParameter" time="0.005"/>
  <testcase classname="tests.parallel.LoginDevice02" name="testSwipeVertically" time="0.048">
    <failure type="java.lang.IllegalArgumentException" message="Please provide env variable [env]!">
      <![CDATA[java.lang.IllegalArgumentException: Please provide env variable [env]!
at driver.DriverFactory.getDriver(DriverFactory.java:62)
at tests.BaseTest.getDriver(BaseTest.java:35)
at tests.parallel.LoginDevice02.testSwipeVertically(LoginDevice02.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testSwipeVertically -->
  <testcase classname="tests.testng.TestNGHooks01" name="testSth03" time="0.009">
    <failure type="java.lang.AssertionError" message="expected [b] but found [a]">
      <![CDATA[java.lang.AssertionError: expected [b] but found [a]
at tests.testng.TestNGHooks01.testSth03(TestNGHooks01.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testSth03 -->
  <testcase classname="tests.testng.TestNGHooks01" name="testSth04" time="0.009">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	[ERR] Wrong message 01 expected [b] but found [a],
	[ERR] Wrong message 02 expected [b] but found [a]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
[ERR] Wrong message 01 expected [b] but found [a],
[ERR] Wrong message 02 expected [b] but found [a]
at tests.testng.TestNGHooks01.testSth04(TestNGHooks01.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- testSth04 -->
  <testcase classname="tests.testng.TestNGHooks01" name="testSth01" time="0.004">
    <failure type="java.lang.RuntimeException" message="FAILED">
      <![CDATA[java.lang.RuntimeException: FAILED
at tests.testng.TestNGHooks01.testSth01(TestNGHooks01.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testSth01 -->
  <testcase classname="tests.testng.TestNGHooks01" name="testSth02" time="0.001">
    <skipped/>
  </testcase> <!-- testSth02 -->
  <testcase classname="tests.testng.BaseTestNG" name="@BeforeTest beforeTest" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTest -->
  <testcase classname="tests.testng.BaseTestNG" name="@BeforeSuite beforeSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeSuite -->
  <testcase classname="tests.testng.BaseTestNG" name="@BeforeTest beforeTest" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTest -->
  <testcase classname="tests.testng.BaseTestNG" name="@BeforeSuite beforeSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeSuite -->
</testsuite> <!-- iPhone 13 -->
